[Card] [Box] Add border as a passthrough prop for Box and Card
Cambly/syntax pull request #381
Opened 2024-04-11 05:51 UTC by somethiiing

I know this was mildly talked about before, but one of the most used prop for `dangerouslySetInlineStyle` is `border`

Setting this type to "string" is awful, I wanted to see if @christianvuerings had a better way of typing something like this.

Also wanted to add this to Card because we're using it in a bunch of places that occasionally needs a border. and rewrapping it another `Box` doesn't feel like great usage.

2024-04-11 05:52 UTC, somethiiing commented on packages/syntax-core/src/Box/Box.tsx
> +  border?: string;
I'm fully aware this is terrible, I was wondering if @christianvuerings had a better way of typing this?

2024-04-11 18:46 UTC, christianvuerings requested changes
Let's not add passthrough props like these - makes it impossible to make them consistent across.

Instead, we should work with design and figure out specific variants

2024-04-11 19:37 UTC, somethiiing commented on packages/syntax-core/src/Box/Box.stories.tsx
> -      {(["sm", "md", "lg", "xl", "full"] as const).map((rounding) => (
removing old variations of rounding on the story

2024-04-11 19:37 UTC, somethiiing commented on packages/syntax-core/src/Box/Box.stories.tsx
> -    <>
tiny tweak to make the story look a little better

2024-04-12 18:12 UTC, btorndorff approved these changes

2024-04-15 19:01 UTC, closed without merging